services:
  - type: web
    name: flask-fire-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sanbul-pwa-flask:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
